version: "3"

vars:
  REGISTRY: ghcr.io/fami-2026

includes:
  server:
    taskfile: ./server/Taskfile.yaml
    dir: ./server
  client:
    taskfile: ./frontend/Taskfile.yaml
    dir: ./frontend

tasks:
  build:
    cmds:
      - task: server:image
      - task: client:image
  deploy:
    cmds:
      - docker compose up -d
