version: "3"

tasks:
  image:
    cmds:
      - docker build -t {{.REGISTRY}}/vge.server:latest .
  publish:
    cmds:
      - docker push {{.REGISTRY}}/vge.server:latest
  deploy:
    cmds:
      - docker compose up -d
  ci:format:
    cmds:
      - gradle spotlessApply
